---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rex-Gearman
no_index:
  directory:
    - t
    - inc
requires:
  Gearman::Client: 0
  Gearman::Worker: 0
  JSON::XS: 0
  Rex: 0.32
resources:
  repository: https://github.com/krimdomu/distributed-rex
version: v0.32.0
